import type {Metadata} from "next";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import {Onest} from 'next/font/google'
import Providers from "@/providers/providers";

const onest = Onest({subsets: ['latin'], weight: ['300', '400', '500', '600', '700', '800', '900']})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <Providers>
            <body
                className={`${onest.className} text-black bg-white`}
            >
            <Header/>
            <div className="bg-[#F0F0F0] rounded-b-[50px] pb-[70px]">
                {children}
            </div>
            <Footer/>
            </body>
        </Providers>
        </html>
    );
}
